import React,{useState}from'react';
import{createRoot}from'react-dom/client';
import'../index.css';
import{Providers,TargetShell}from'./shared';
import{useAuth}from'../context/AuthContext';
import{AgentDashboard}from'../components/agent/AgentDashboard';
import{AttendancePage}from'../components/common/AttendancePage';
import{SalesSummaryPage}from'../components/common/SalesSummaryPage';
import{PersonalProfileKycPage}from'../components/common/PersonalProfileKycPage';
import CommissionPaymentPage from'../components/common/CommissionPaymentPage';
import{MessageRoomPage}from'../components/common/MessageRoomPage';
import{Home,CalendarCheck,BarChart3,FileText,User,Wallet,MessageSquare,Settings,LogOut}from'lucide-react';
type Tab='home'|'attendance'|'sales'|'reports'|'profile'|'payment'|'messages'|'settings';
const tabs:{id:Tab;label:string;icon:any}[]=[{id:'home',label:'Home',icon:Home},{id:'attendance',label:'Attendance',icon:CalendarCheck},{id:'sales',label:'Sales',icon:BarChart3},{id:'reports',label:'Performance',icon:FileText},{id:'profile',label:'Profile / KYC',icon:User},{id:'payment',label:'Payment',icon:Wallet},{id:'messages',label:'Messages',icon:MessageSquare},{id:'settings',label:'Settings',icon:Settings}];
const SettingsPage=()=>{const{currentUser,logout}=useAuth();return <section className="rounded-3xl border border-slate-200 bg-white p-5"><h2 className="text-xl font-black">Agent Settings</h2><p className="mt-2 text-xs text-slate-500">Signed in as {currentUser?.name||'Agent'}.</p><button onClick={()=>void logout()} className="mt-4 rounded-xl bg-slate-900 px-4 py-3 text-xs font-black text-white"><LogOut className="mr-1 inline h-4 w-4"/>Log out</button></section>};
const Workspace=()=>{const{currentUser}=useAuth();const[tab,setTab]=useState<Tab>('home');if(!currentUser)return null;const render=()=>{if(tab==='home')return <AgentDashboard/>;if(tab==='attendance')return <AttendancePage/>;if(tab==='sales')return <SalesSummaryPage/>;if(tab==='reports')return <SalesSummaryPage/>;if(tab==='profile')return <PersonalProfileKycPage/>;if(tab==='payment')return <CommissionPaymentPage/>;if(tab==='messages')return <MessageRoomPage/>;return <SettingsPage/>};return <div className="min-h-screen bg-[#f5f8fc] text-[#14213d] pb-24"><header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 px-4 py-3 shadow-sm"><h1 className="text-lg font-black">DD WORLD Agent App</h1><p className="text-[11px] text-slate-500">{currentUser.name||'Agent'} • Personal Field Workspace</p></header><div className="mx-auto max-w-3xl px-3 pt-3"><div className="flex gap-2 overflow-x-auto pb-1">{tabs.map(({id,label,icon:Icon})=><button key={id} onClick={()=>setTab(id)} className={`shrink-0 rounded-xl border px-3 py-2 text-[11px] font-black flex items-center gap-1.5 ${tab===id?'border-slate-900 bg-slate-900 text-white':'border-slate-200 bg-white text-slate-600'}`}><Icon className="h-4 w-4"/>{label}</button>)}</div></div><main className="mx-auto max-w-3xl px-3 py-4">{render()}</main></div>};
createRoot(document.getElementById('root')!).render(<Providers><TargetShell target="agent"><Workspace/></TargetShell></Providers>);
