import React,{useEffect,useMemo,useState} from 'react';
import {supabase} from '../../services/supabase';
const money=(x:number)=>`Rs. ${Number(x||0).toLocaleString('en-LK',{maximumFractionDigits:2})}`;
const s=(x:any)=>String(x??'').trim(); const n=(x:any)=>Number(String(x??'').replace(/,/g,'').replace(/[^0-9.-]/g,''))||0;
const pick=(r:any,ks:string[])=>{const k=Object.keys(r).find(x=>ks.some(q=>x.toLowerCase().replace(/\s/g,'').includes(q)));return k?r[k]:''};
const parse=(t:string)=>{const l=t.replace(/\r/g,'').split('\n').filter(Boolean);if(!l.length)return[];const d=l[0].includes('\t')?'\t':',';const sp=(x:string)=>x.split(d).map(v=>v.trim().replace(/^"|"$/g,''));const h=sp(l[0]);return l.slice(1).map(x=>{const r:any={};sp(x).forEach((v,i)=>r[h[i]||`c${i}`]=v);return r})};
const normalize=(rs:any[])=>rs.map((r,i)=>{const appSales=n(pick(r,['appactivation','app activation'])),ivrSales=n(pick(r,['ivreactivation','ivr activation'])),appAmount=n(pick(r,['amount1','app amount'])),ivrAmount=n(pick(r,['ivramount','ivr amount'])),ri=n(pick(r,['retentionivr','retention ivr'])),ra=n(pick(r,['retentionapp','retention app']));return {...r,name:s(pick(r,['name']))||`Row ${i+1}`,agentCode:s(pick(r,['agentcode','agent code','code'])),appSales,ivrSales,appAmount,ivrAmount,retentionIvr:ri,retentionApp:ra,reduction:n(pick(r,['reduction'])),total:n(pick(r,['total'])),finalized:n(pick(r,['finalized','finalised'])),agentPayment:appAmount+ivrAmount,teamLeaderCommission:ri+ra}});
export default function CommissionPaymentPage(){
 const [me,setMe]=useState<any>(null),[report,setReport]=useState<any>(null),[agentPayments,setAgentPayments]=useState<any[]>([]),[users,setUsers]=useState<any[]>([]),[subs,setSubs]=useState<any[]>([]),[issues,setIssues]=useState<any[]>([]),[month,setMonth]=useState(new Date().toISOString().slice(0,7)),[product,setProduct]=useState('sayuru'),[raw,setRaw]=useState(''),[addition,setAddition]=useState(''),[dialogRef,setDialogRef]=useState(''),[busy,setBusy]=useState(false);
 const role=s(me?.role).toLowerCase(),owner=role==='owner',tl=role==='team_leader',agent=role==='agent',dialog=role==='dialog_officer';
 const rows=useMemo(()=>Array.isArray(report?.report_rows)?report.report_rows:[],[report]);
 const myRows=agent?agentPayments:rows;
 const teamRows=useMemo(()=>tl?rows.filter(r=>users.some(u=>u.role==='agent'&&u.team_id===me?.team_id&&s(u.agent_code)===s(r.agentCode))):[],[tl,rows,users,me]);
 const load=async()=>{const {data:a}=await supabase.auth.getUser();if(!a.user)return;const [{data:p},{data:r},{data:u}]=await Promise.all([supabase.from('users').select('*').eq('auth_user_id',a.user.id).maybeSingle(),supabase.from('commission_reports').select('*').eq('month_start',`${month}-01`).eq('product',product).order('uploaded_at',{ascending:false}).limit(1),supabase.from('users').select('id,name,agent_code,role,team_id').order('name')]);setMe(p);setReport(r?.[0]||null);setUsers(u||[]);if(agent){const {data:ap}=await supabase.from('commission_agent_payments').select('*').eq('report_id',r?.[0]?.id||'00000000-0000-0000-0000-000000000000');setAgentPayments(ap||[])}else setAgentPayments([]);if(r?.[0]){const [{data:x},{data:i}]=await Promise.all([supabase.from('commission_team_submissions').select('*').eq('report_id',r[0].id).order('submitted_at',{ascending:false}),supabase.from('commission_payment_issues').select('*').eq('report_id',r[0].id).order('reported_at',{ascending:false})]);setSubs(x||[]);setIssues(i||[])}};
 useEffect(()=>{load()},[month,product,agent]);
 const upload=async(file:File)=>{setBusy(true);try{const text=await file.text(),rr=normalize(parse(text));if(!rr.length||!rr.some(x=>x.agentCode))throw Error('Agent Code සහිත final report එකක් අවශ්‍යයි.');const {data:a}=await supabase.auth.getUser();const {error}=await supabase.from('commission_reports').upsert({month_start:`${month}-01`,product,file_name:file.name,raw_file_text:text,report_rows:rr,uploaded_by:a.user?.id,status:'RECEIVED'},{onConflict:'month_start,product'});if(error)throw error;await load()}catch(e:any){alert(e.message||'Upload failed')}finally{setBusy(false)}};
 const approve=async()=>{if(!report)return;const {data:a}=await supabase.auth.getUser();const {error}=await supabase.from('commission_reports').update({status:'OWNER_APPROVED',owner_approved_by:a.user?.id,owner_approved_at:new Date().toISOString(),owner_addition:n(addition)}).eq('id',report.id);if(error)alert(error.message);else load()};
 const download=()=>{if(!report)return;const h=['Name','Agent Code','App Sales','App Amount','IVR Sales','IVR Amount','Retention IVR','Retention App','Reduction','Total','Finalized','Agent Payment','TL Commission'];const csv=[h.join(','),...rows.map((r:any)=>[r.name,r.agentCode,r.appSales,r.appAmount,r.ivrSales,r.ivrAmount,r.retentionIvr,r.retentionApp,r.reduction,r.total,r.finalized,r.agentPayment,r.teamLeaderCommission].map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${month}-${product}-dialog-final-report.csv`;a.click();URL.revokeObjectURL(a.href)};
 const submitTeam=async()=>{if(!report||!me)return;const parsed=raw.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const p=line.split('|').map(x=>x.trim()),r=rows.find(x=>s(x.agentCode)===p[1]);return r?{name:r.name,agentCode:p[1],amount:n(p[2]),appSales:r.appSales,ivrSales:r.ivrSales,agentPayment:r.agentPayment,teamLeaderCommission:r.teamLeaderCommission,ezCashNumber:p[3]||''}:null}).filter(Boolean);if(!parsed.length)return alert('Format: Agent Name | Agent Code | Amount | EZ Cash Number');const grouped:any={};parsed.forEach((r:any)=>(grouped[r.ezCashNumber]??=[]).push(r));for(const [num,arr] of Object.entries(grouped) as any){if(arr.reduce((x:number,r:any)=>x+r.amount,0)>150000)return alert(`eZ Cash ${num} exceeds Rs.150,000.`)}const total=parsed.reduce((x:number,r:any)=>x+r.amount,0);const teamName=users.find(u=>u.id===me.team_id)?.name||'My Team';const {error}=await supabase.from('commission_team_submissions').upsert({report_id:report.id,team_id:me.team_id,team_name:teamName,team_leader_id:me.id,ez_cash_groups:Object.entries(grouped).map(([number,arr]:any)=>({number,agents:arr,subtotal:arr.reduce((x:number,r:any)=>x+r.amount,0)})),team_total:total,final_total:total,status:'SUBMITTED'},{onConflict:'report_id,team_leader_id'});if(error)alert(error.message);else{setRaw('');load()}};
 const issue=async(r:any)=>{const got=prompt(`Expected ${money(r.agent_amount??r.agentPayment)}. Received?`,String(r.agent_amount??r.agentPayment));if(got===null)return;const reason=prompt('Issue reason?');if(!reason)return;await supabase.from('commission_payment_issues').insert({report_id:report.id,agent_code:r.agent_code||r.agentCode,agent_name:r.agent_name||r.name,expected_amount:r.agent_amount??r.agentPayment,received_amount:n(got),reason,reported_by:me.id});load()};
 return <div className="min-h-screen bg-slate-950 text-white p-4 md:p-6"><div className="max-w-7xl mx-auto space-y-5"><header className="rounded-2xl border border-white/10 bg-white/5 p-5"><div className="text-xs tracking-widest text-emerald-300">PAGE 7 · OFFICIAL</div><h1 className="text-2xl font-bold">Commission / Payment</h1><p className="text-sm text-slate-300">Dialog Final Report → Owner → Team Leader → Agent</p><div className="flex flex-wrap gap-3 mt-4"><input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="rounded-xl bg-slate-900 border border-white/10 px-3 py-2"/><select value={product} onChange={e=>setProduct(e.target.value)} className="rounded-xl bg-slate-900 border border-white/10 px-3 py-2"><option value="sayuru">Sayuru</option><option value="govimithuru">Govi Mithuru</option></select></div></header>
 {(dialog||owner)&&<section className="rounded-2xl border border-white/10 bg-white/5 p-5 space-y-3"><h2 className="font-semibold">Dialog Final Report</h2>{dialog&&<input type="file" accept=".csv,.tsv,.txt" disabled={busy} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])} className="block w-full text-sm"/>}{report&&<div className="flex flex-wrap gap-2 items-center"><span className="px-3 py-1 rounded-full bg-emerald-500/20">{report.status}</span><span className="text-sm">{report.file_name}</span><button onClick={download} className="px-3 py-1 rounded-lg bg-white/10">Download phone copy</button></div>}{owner&&report&&<div className="flex gap-2"><input value={addition} onChange={e=>setAddition(e.target.value)} placeholder="Owner additional amount (optional)" className="flex-1 rounded-xl bg-slate-900 border border-white/10 px-3 py-2"/><button onClick={approve} className="px-4 py-2 rounded-xl bg-emerald-600">✓ OWNER APPROVE</button></div>}</section>}
 {owner&&report&&<section className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold mb-3">Full Dialog Final Report — Owner Only</h2><div className="overflow-auto"><table className="min-w-full text-xs"><thead><tr className="text-slate-400"><th className="p-2 text-left">Agent</th><th>Code</th><th>App</th><th>IVR</th><th>Agent Amount</th><th>TL Commission</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.agentCode+r.name} className="border-t border-white/5"><td className="p-2">{r.name}</td><td>{r.agentCode||'UNASSIGNED'}</td><td>{r.appSales}</td><td>{r.ivrSales}</td><td>{money(r.agentPayment)}</td><td>{money(r.teamLeaderCommission)}</td></tr>)}</tbody></table></div></section>}
 {tl&&report?.status==='OWNER_APPROVED'&&<section className="rounded-2xl border border-white/10 bg-white/5 p-5 space-y-3"><h2 className="font-semibold">Team Payment → Owner</h2><p className="text-xs text-slate-400">Agent Name | Agent Code | Amount | EZ Cash Number. One number can contain 1 or more agents.</p><textarea rows={10} value={raw} onChange={e=>setRaw(e.target.value)} placeholder="Lahiru Sampath | 9066 | 64900 | 07656544566" className="w-full rounded-xl bg-slate-900 border border-white/10 p-3 font-mono text-sm"/><div className="text-xs text-amber-300">⚠️ Each eZ Cash number maximum: Rs.150,000</div><button onClick={submitTeam} className="px-5 py-2 rounded-xl bg-emerald-600">SUBMIT TO OWNER</button></section>}
 {owner&&report&&<section className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold mb-3">Team Leader Submissions</h2>{subs.length?subs.map((x:any)=><div key={x.id} className="rounded-xl border border-white/10 p-4 mb-2"><div className="flex justify-between"><b>{x.team_name}</b><b>{money(x.final_total)}</b></div><pre className="text-xs text-slate-300 mt-2 whitespace-pre-wrap">{JSON.stringify(x.ez_cash_groups,null,2)}</pre><div className="flex flex-wrap gap-2 mt-2"><input value={dialogRef} onChange={e=>setDialogRef(e.target.value)} placeholder="Dialog reference" className="rounded-lg bg-slate-900 border border-white/10 px-2 py-1"/><button onClick={async()=>{await supabase.from('commission_team_submissions').update({status:'OWNER_APPROVED',owner_reviewed_by:me.id,owner_reviewed_at:new Date().toISOString(),owner_addition:n(addition),final_total:n(x.team_total)+n(addition)}).eq('id',x.id);load()}} className="px-3 py-1 rounded-lg bg-emerald-600">✓ APPROVE / SEND TO DIALOG</button></div></div>):<p className="text-sm text-slate-400">No Team Leader submission yet.</p>}</section>}
 {dialog&&subs.some(x=>x.status==='OWNER_APPROVED')&&<section className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold">Dialog Payment Confirmation</h2>{subs.filter(x=>x.status==='OWNER_APPROVED').map((x:any)=><div key={x.id} className="flex justify-between border-t border-white/5 py-3"><span>{x.team_name} · {money(x.final_total)}</span><button onClick={async()=>{await supabase.from('commission_team_submissions').update({status:'DIALOG_PAID',dialog_paid_at:new Date().toISOString(),dialog_reference:dialogRef}).eq('id',x.id);load()}} className="px-3 py-1 rounded-lg bg-emerald-600">DIALOG PAID</button></div>)}</section>}
 {(agent||tl)&&((agent&&agentPayments.length>0)||tl)&&<section className="rounded-2xl border border-white/10 bg-white/5 p-5"><h2 className="font-semibold mb-3">{agent?'My Payment':'My Team Agent Payments'}</h2>{(agent?myRows:teamRows).map((r:any)=><div key={r.agentCode||r.agent_code} className="rounded-xl border border-white/10 p-4 mb-2"><b>{r.name||r.agent_name} · {r.agentCode||r.agent_code}</b><div className="text-sm text-slate-300 mt-1">App: {r.appSales??r.app_sales} · IVR: {r.ivrSales??r.ivr_sales}</div><div className="text-lg font-bold mt-2">Agent Amount: {money(r.agentPayment??r.agent_amount)}</div>{agent&&<div className="flex gap-2 mt-3"><button onClick={async()=>{await supabase.from('commission_agent_payments').update({status:'CONFIRMED',received_at:new Date().toISOString()}).eq('id',r.id);load()}} className="px-3 py-2 rounded-lg bg-emerald-600">✓ PAYMENT RECEIVED</button><button onClick={()=>issue(r)} className="px-3 py-2 rounded-lg bg-red-500/80">REPORT PAYMENT ISSUE</button></div>}</div>)}</section>}
 {(owner||tl)&&issues.length>0&&<section className="rounded-2xl border border-red-400/20 bg-red-500/5 p-5"><h2 className="font-semibold text-red-200">Payment Issues</h2>{issues.map((i:any)=><div key={i.id} className="text-sm py-2 border-t border-white/5">{i.agent_name} ({i.agent_code}) · Expected {money(i.expected_amount)} · Received {money(i.received_amount)} · {i.reason}</div>)}</section>}
 </div></div>;
}
