-- Aggregate Dialog report imports used by the Sales Performance page.
-- The report pivot screenshots contain aggregate counts, not row-level activation IDs.
-- Therefore these records support count reconciliation only and must never auto-confirm individual sales.

CREATE TABLE IF NOT EXISTS public.dialog_report_import_rows (
  id bigint generated by default as identity primary key,
  created_at timestamptz NOT NULL DEFAULT now(),
  agent_code text,
  agent_name text,
  product_type text NOT NULL,
  activation_count integer NOT NULL DEFAULT 0 CHECK (activation_count >= 0),
  report_month date NOT NULL,

  -- Client compatibility fields used by the reconciliation UI.
  report_period text,
  product text,
  method text,
  dimension text,
  label text,
  subscriber_count integer,
  source_filename text,
  imported_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  imported_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS dialog_report_import_rows_lookup_idx
  ON public.dialog_report_import_rows (report_month, lower(product_type), method, dimension);

CREATE INDEX IF NOT EXISTS dialog_report_import_rows_agent_idx
  ON public.dialog_report_import_rows (report_month, agent_code, agent_name);

ALTER TABLE public.dialog_report_import_rows ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS dialog_report_rows_authenticated_read ON public.dialog_report_import_rows;
DROP POLICY IF EXISTS dialog_report_rows_owner_insert ON public.dialog_report_import_rows;
DROP POLICY IF EXISTS dialog_report_rows_owner_delete ON public.dialog_report_import_rows;
DROP POLICY IF EXISTS dialog_report_import_rows_owner_or_audit_select ON public.dialog_report_import_rows;
DROP POLICY IF EXISTS dialog_report_import_rows_owner_insert ON public.dialog_report_import_rows;
DROP POLICY IF EXISTS dialog_report_import_rows_owner_delete ON public.dialog_report_import_rows;

CREATE POLICY dialog_report_import_rows_owner_or_audit_select
  ON public.dialog_report_import_rows
  FOR SELECT TO authenticated
  USING (
    public.is_owner()
    OR EXISTS (
      SELECT 1
      FROM public.users u
      WHERE u.auth_user_id = (SELECT auth.uid())
        AND u.role = 'dialog_officer'
        AND u.status = 'active'
        AND u.employment_status = 'ACTIVE'
        AND u.id_approval_status = 'APPROVED'
    )
  );

CREATE POLICY dialog_report_import_rows_owner_insert
  ON public.dialog_report_import_rows
  FOR INSERT TO authenticated
  WITH CHECK (public.is_owner() AND imported_by = (SELECT auth.uid()));

CREATE POLICY dialog_report_import_rows_owner_delete
  ON public.dialog_report_import_rows
  FOR DELETE TO authenticated
  USING (public.is_owner());

REVOKE ALL ON TABLE public.dialog_report_import_rows FROM anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE public.dialog_report_import_rows TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.dialog_report_import_rows_id_seq TO authenticated;

COMMENT ON TABLE public.dialog_report_import_rows IS
  'Aggregate Dialog report rows for count reconciliation. These records do not individually verify sales.';

NOTIFY pgrst, 'reload schema';
NOTIFY pgrst, 'reload config';
